
version: 1.0.{build}

#image: Ubuntu

platform:
  - Any CPU
install:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- c:\"Program Files"\"Microsoft SQL Server"\140\"Setup Bootstrap"\SQL2017\setup.exe /qs /ACTION=Install /FEATURES=SQL_INST_MR /INSTANCENAME=MSSQLSERVER /IACCEPTSQLSERVERLICENSETERMS  /IACCEPTROPENLICENSETERMS
  #- cd c:\ && dir /s setup.exe
  #- nuget
  #- cmd: nuget restore  
  #- sh: find . -name \java* -print
  #- ps: get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
  - ps: cmake --version
  - ps: |
      $app = Get-WmiObject -Class Win32_Product -Filter "Name = 'cmake'"
      $app.Uninstall()
  - ps: (New-Object System.Net.WebClient).DownloadFile("https://cmake.org/files/v3.10/cmake-3.10.3-win64-x64.msi", "C:\Windows\Temp\cmake.msi")
  - ps: msiexec /i "C:\Windows\Temp\cmake.msi" /qn
  - ps: cmake --version
build: off
 
  #verbosity: minimal
